# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='liked_books',
        ),
        migrations.RemoveField(
            model_name='users',
            name='uploaded_books',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_books',
            field=models.ManyToManyField(related_name='liked_users', to='likes.Users'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_books',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='likes.Users'),
            preserve_default=False,
        ),
    ]
